### ISSUE TITLE
Unique listener metrics

### ISSUE THREAD

**Issue by kookster** [PRX/castle.prx.org#110]
In the IAB v2, and some competing products like podtrac, there are measures of unique listeners, not just downloads, to a show (e.g. users who listen to multiple episodes in some timeframe, then consolidated to a single unique listener for that time frame).

Would be good to have such a metric as well, at the podcast level probably?

**Comment by cavis** [comment]
What timeframe(s) would we roll this up to?  Maybe pick a few, like a rolling day/week/month?  Seems like we'd have to decide on those ahead of time, as there's no easy way to rollup BQ -> PG and then do a _just-in-time_ rollup to an arbitrary timeframe.

**Comment by svevang** [comment]
Potential Daily Rollups.  this could be rolling window, or could just be a single look back 

uniques per podcast:
- last week 
- last month
- last year 

- Same but for last 5 episodes
- Same but for all episodes (or other subset?)

**Comment by svevang** [comment]
So the current approach (which should feed into https://github.com/PRX/metrics.prx.org/issues/413) is to create an aggregate of uniques for the following:

last week (single set of values -- rolling)
last 28 days (single set of values -- rolling)
weekly (refreshed as time elapses)
monthly (refreshed as time elapses)
