### ISSUE TITLE
Geolocation facet

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#15]
Support faceting by location.  Will need to map IP -> geolocation (in bigquery), and then aggregate that somehow based on a zoom level.

**Comment by kookster** [comment]
@cavis can we call this done?

**Comment by cavis** [comment]
I wouldn't yet.  Actual castle API PR coming soon to github repo near you.

**Comment by kookster** [comment]
okay, adding to Oscar then

**Comment by cavis** [comment]
It's #20

**Comment by cavis** [comment]
Merge'd!
