### ISSUE TITLE
Async caching

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#24]
Add some generic background workers for caching certain kinds of data in redis.  In cases where we want to make the queries on a cron, instead of triggering them from http requests.

**Comment by cavis** [comment]
Rolled up totals data _seems_ to be there in staging/prod.  But not seeing the log messages I would expect.  Going to look into that a bit more before closing this.

**Comment by gcampo88** [comment]
should be logging now from #32

**Comment by cavis** [comment]
Confirmed!  Logging!
