### ISSUE TITLE
Real authorization

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#25]
Map PRX account-ids to feeder podcasts/episodes the user should be able to see.

- [ ] Google cloud function on a cron that:
  - [ ] Queries feeder for a list of all podcasts (and extrapolate the account-id from the link???)
  - [ ] Queries feeder for a list of episodes, for each podcast
  - [ ] Inserts/overwrites BQ tables containing podcasts (id, title, accountid) and episodes (guid, title, accountid)
- [ ] Update castle SQL to filter everything based on account-ids in the auth token

**Comment by pkarman** [comment]
@cavis priority please
