### ISSUE TITLE
Calendar based intervals

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#27]
New calendar-based `?interval=` rollup params:

- [ ] ~~Quarter~~
- [x] Month
- [x] Week

And just continue to rollup based on UTC for this one.

**Comment by pkarman** [comment]
@cavis priority please

**Comment by cavis** [comment]
This one's feeling like a definite UI need.

**Comment by cavis** [comment]
Dropped "quarter" as there didn't seem to be a definite need there yet.  And the others are now deploy'd!
