### ISSUE TITLE
Better group caching

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#29]
Currently, when you `?group=something`, it's behind a single response cache.

This should really be a partitioned cache, where the current-day BQ-partition is cached for 5 minutes, and all other BQ-partitions are cached for much longer.

The trick here is that the "Top 10 cities" can change depending on if you ask for today vs the 30 days before that.  So would need to figure out a way to query for specific cities when asking for today, instead of doing the Top-N thing.  Not sure how complex that would be, at the moment.

**Comment by pkarman** [comment]
@cavis Priority please

**Comment by cavis** [comment]
Will wait for this to become a UX problem.

**Comment by cavis** [comment]
Postgres rollups make this unnecessary.
