### ISSUE TITLE
Profile and optimize API reads

### ISSUE THREAD

**Issue by pkarman** [PRX/castle.prx.org#37]
metrics.prx.org makes many calls to fetch data. Profile and optimize those calls so that they are <1sec each (currently 2-3sec each).

![screen shot 2017-10-12 at 11 09 34 am](https://user-images.githubusercontent.com/1205061/31506721-dfebcd9a-af3d-11e7-8777-5e020482fabb.png)

**Comment by cavis** [comment]
My gut feeling is ~3 seconds is fairly normal for bigquery.  Will check that, though.

The current logic is to only fetch from BQ on-demand.  The "latest slice" you ask for (the current day/hour/15-min) is cached for 15 seconds, and older slices are cached for 12 hours.  Could increase the TTL especially for older intervals ... but no way to really speed up the initial fetch.

So if we really want to get response times down, some options:
1. Move everything to a background worker that does rollups into redis.  Would have to rollup the "latest slice" fairly frequently, to make data seem live.
2. Just increase the "latest slice" TTL, and figure out some other way to update it.  Maybe the ingest-lambda manually increments redis counts?  Or a castle-worker does it?
