### ISSUE TITLE
Filters for geo/agent groups

### ISSUE THREAD

**Issue by cavis** [PRX/castle.prx.org#77]
Allow filtering a subset of ranks/groupings:

- [x] `group=geosubdiv` filter by country
- [ ] `group=agentname` filter by os and type
- [ ] `group=agenttype` filter by os

**Comment by pkarman** [comment]
@cavis can you please score this and move to backlog?

**Comment by cavis** [comment]
I believe this is the last ticket for Metrics mapping functionality ... should probably just get it done.

**Comment by cavis** [comment]
No plans on agent os/type filtering right now.  Until needed for a UI feature.
